# Generated by Django 5.2.5 on 2025-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
        migrations.AddField(
            model_name='vendor',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
