# Generated by Django 5.2.5 on 2025-10-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendoraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='LinkedIn URL'),
        ),
    ]
