# Generated by Django 5.2.5 on 2025-08-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_vendor_client_clientvendorlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
