# Generated by Django 5.2.5 on 2025-09-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_vendor_city_vendor_country_vendor_notes_vendor_state_and_more'),
        ('vendors', '0006_remove_vendor_website_vendor_street_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvendorlink',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_clients', to='vendors.vendor'),
        ),
    ]
