# Generated by Django 5.2.5 on 2025-09-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clientvendorlink_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='domain_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='domain_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
