# Generated by Django 5.2.5 on 2025-08-14 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='client',
        ),
        migrations.CreateModel(
            name='ClientVendorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Vendor', 'Vendor'), ('Prime Vendor', 'Prime Vendor'), ('Implementation Partner', 'Implementation Partner')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_vendors', to='clients.client')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_clients', to='clients.vendor')),
            ],
            options={
                'unique_together': {('client', 'vendor', 'role')},
            },
        ),
    ]
