# Generated by Django 5.2.5 on 2025-10-23 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('ssn', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('other_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('skype_id', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('exp', models.BooleanField(default=False)),
                ('gk', models.BooleanField(default=False)),
                ('gk_move_in_date', models.DateField(blank=True, null=True)),
                ('us_entry_date', models.DateField(blank=True, null=True)),
                ('recruiter', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('pref_location', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.skill')),
                ('visa_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.visa')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='sales.consultant')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('university_name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=100)),
                ('year_of_completion', models.DateField()),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='sales.consultant')),
            ],
        ),
    ]
