# Generated by Django 5.2.5 on 2025-10-26 05:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientaddress'),
        ('sales', '0002_consultant_consultantaddress_consultanteducation'),
        ('vendors', '0008_vendor_linkedin_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, null=True)),
                ('vendor_response', models.CharField(choices=[('ClientSubmitted', 'Submitted to Client'), ('ClientRejected', 'Rejected by Client'), ('ClientSelected', 'Selected by Client')], default='ClientSubmitted', max_length=50)),
                ('resume_passed_to_client', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='sales.consultant')),
                ('end_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_submissions', to='clients.client')),
                ('implementation_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impl_partner_submissions', to='vendors.vendor')),
                ('marketer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketer_submissions', to=settings.AUTH_USER_MODEL)),
                ('prime_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prime_vendor_submissions', to='vendors.vendor')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_submissions', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-submission_date'],
                'unique_together': {('consultant', 'vendor', 'prime_vendor', 'implementation_partner', 'end_client')},
            },
        ),
    ]
