# Generated by Django 5.2.5 on 2025-10-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_skills', to='sales.skill'),
        ),
    ]
