# Generated by Django 5.2.5 on 2025-10-26 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('sales', '0004_submission_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='marketer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketer_submissions', to='adminpanel.marketer'),
        ),
    ]
