# Generated by Django 5.2.5 on 2025-10-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_submission_marketer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='technology',
            new_name='skill',
        ),
    ]
