DOMAIN_CHOICES = [
    "Banking & Financial Services",
    "Insurance",
    "Healthcare & Life Sciences",
    "Pharmaceuticals",
    "Retail & E-Commerce",
    "Telecommunications",
    "Manufacturing",
    "Energy & Utilities",
    "Oil & Gas",
    "Media & Entertainment",
    "Travel & Hospitality",
    "Transportation & Logistics",
    "Supply Chain & Warehousing",
    "Government & Public Sector",
    "Education & E-Learning",
    "Automotive",
    "Aerospace & Defense",
    "Technology & Software",
    "Consumer Electronics",
    "Agriculture & Food Processing",
    "Real Estate & Construction",
    "Professional Services & Consulting",
    "Non-Profit & NGOs",
    "Cybersecurity",
    "Cloud & SaaS Providers",
]